import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
const root = fileURLToPath(new URL("../../../", import.meta.url));
const web = resolve(root, "web"), require = createRequire(resolve(web, "package.json"));
const ts = require("typescript");
const configPath = resolve(web, "tsconfig.ui-regression.json");
const read = ts.readConfigFile(configPath, ts.sys.readFile);
assert.equal(read.error, undefined, "strict config must be readable");
const config = ts.parseJsonConfigFileContent(read.config, ts.sys, web);
assert.deepEqual(config.errors, [], "strict config must be valid");
assert.equal(config.options.strict, true); assert.equal(config.options.noEmit, true); assert.equal(config.options.skipLibCheck, false);
assert.ok(config.fileNames.length > 0, "zero-file strict check is not success");
for (const path of ["tests/helpers/run-ui-foundation-browser.mts", "tests/helpers/ui-foundation-status-authority.mts", "tests/ui-foundation-status.test.mts", "tests/ui-regression/draft-flow.test.mts", "tests/ui-regression/form-content-driver.test.mts", "tests/ui-regression/keyboard-navigation.test.mts"]) assert.ok(config.fileNames.some(name => resolve(name) === resolve(web, path)), "missing actual strict root: " + path);
console.log(JSON.stringify({ strictRoots: config.fileNames.length, strict: true, skipLibCheck: false, noEmit: true }));
const result = spawnSync(process.execPath, [resolve(web, "node_modules/@typescript/native/bin/tsc"), "--noEmit", "-p", configPath], { cwd: web, stdio: "inherit", env: process.env });
if (result.error) throw result.error;
assert.equal(result.signal, null, "strict compiler was interrupted");
process.exit(result.status ?? 1);
