const auditActionLabels: Record<string, string> = {
  "app.settings.update": "アプリ設定を更新",
  "app.settings.test_email": "テストメールを送信",
  "api_tokens.create": "APIトークンを作成",
  "api_tokens.revoke": "APIトークンを失効",
  "api_tokens.rotate": "APIトークンを再生成",
  "archive.artifact.delete": "録画ファイルを削除",
  "archive.artifact.download": "録画ファイルをダウンロード",
  "archive.artifact.rename": "録画ファイル名を変更",
  "archive.artifact.share.create": "録画ファイルの共有リンクを作成",
  "archive.artifact.share.revoke": "録画ファイルの共有リンクを無効化",
  "archive_destinations.create": "Drive保存先を作成",
  "archive_destinations.delete": "Drive保存先を削除",
  "archive_destinations.update": "Drive保存先を更新",
  "archive_profiles.create": "Archiveプロファイルを作成",
  "archive_profiles.delete": "Archiveプロファイルを削除",
  "archive_profiles.update": "Archiveプロファイルを更新",
  "auth.login": "管理画面へログイン",
  "auth.logout": "管理画面からログアウト",
  "auth.change_password": "パスワードを変更",
  "auth.email.change_request": "メールアドレス変更を申請",
  "auth.email.confirm": "メールアドレス変更を確認",
  "auth.oauth.login": "OAuthでログイン",
  "auth.oauth.provision_user": "OAuthユーザーを作成",
  "auth.oauth.start": "OAuthログインを開始",
  "auth.oauth_link.create": "OAuth連携を作成",
  "auth.oauth_link.delete": "OAuth連携を解除",
  "discord_configs.create": "Discord BOT設定を作成",
  "discord_configs.delete": "Discord BOT設定を削除",
  "discord_configs.update": "Discord BOT設定を更新",
  "caption_profiles.create": "Captionプロファイルを作成",
  "caption_profiles.delete": "Captionプロファイルを削除",
  "caption_profiles.update": "Captionプロファイルを更新",
  "encoder_profiles.create": "Encoderプロファイルを作成",
  "encoder_profiles.delete": "Encoderプロファイルを削除",
  "encoder_profiles.update": "Encoderプロファイルを更新",
  "incidents.acknowledge": "インシデントを確認済みに変更",
  "incidents.resolve": "インシデントを解決済みに変更",
  "integrations.drive_destination.create": "Drive保存先を作成",
  "integrations.drive_destination.delete": "Drive保存先を削除",
  "integrations.drive_destination.update": "Drive保存先を更新",
  "integrations.oauth_account.connect": "OAuth接続アカウントを接続",
  "integrations.oauth_account.create": "OAuth接続アカウントを作成",
  "integrations.oauth_account.delete": "OAuth接続アカウントを削除",
  "integrations.oauth_account.update": "OAuth接続アカウントを更新",
  "integrations.oauth_provider.create": "OAuthプロバイダを作成",
  "integrations.oauth_provider.delete": "OAuthプロバイダを削除",
  "integrations.oauth_provider.update": "OAuthプロバイダを更新",
  "mfa.enroll": "MFAを登録",
  "mfa.disable": "MFAを無効化",
  "mfa.recovery_codes.regenerate": "MFAリカバリーコードを再発行",
  "mfa.verify": "MFAを確認",
  "nodes.configure_token.rotate": "Node設定トークンを再生成",
  "nodes.delete": "Nodeを削除",
  "nodes.registration_token.create": "Node登録トークンを発行",
  "nodes.runtime_token.rotate": "Node Runtime Tokenを再生成",
  "nodes.update": "Nodeを更新",
  "notification_channels.create": "通知先を作成",
  "notification_channels.delete": "通知先を削除",
  "notification_channels.test": "通知テストを送信",
  "notification_channels.update": "通知先を更新",
  "oauth_accounts.create": "OAuth接続アカウントを作成",
  "oauth_accounts.delete": "OAuth接続アカウントを削除",
  "oauth_accounts.update": "OAuth接続アカウントを更新",
  "oauth_providers.create": "OAuthプロバイダを作成",
  "oauth_providers.delete": "OAuthプロバイダを削除",
  "oauth_providers.update": "OAuthプロバイダを更新",
  "overlay_profiles.create": "Overlayプロファイルを作成",
  "overlay_profiles.delete": "Overlayプロファイルを削除",
  "overlay_profiles.update": "Overlayプロファイルを更新",
  "passkeys.delete": "Passkeyを削除",
  "passkeys.registration.start": "Passkey登録を開始",
  "remediation.approve": "復旧操作を承認",
  "remediation.execute": "復旧操作を実行",
  "roles.create": "ロールを作成",
  "roles.delete": "ロールを削除",
  "roles.update": "ロールを更新",
  "secrets.update": "シークレットを更新",
  "security.settings.update": "セキュリティ設定を更新",
  "services.assign": "Nodeを割り当て",
  "services.delete": "Nodeを削除",
  "services.runtime_config.read": "Nodeが実行設定を参照",
  "services.runtime_config.preview": "Node実行設定をプレビュー",
  "services.unassign": "Nodeの割り当てを解除",
  "setup.first_admin": "初期管理者を作成",
  "streams.create": "配信枠を作成",
  "streams.discord_youtube_notify": "DiscordへYouTube配信を通知",
  "streams.mark_failed": "配信を失敗状態に変更",
  "streams.preview_link.create": "プレビューリンクを作成",
  "streams.retry_upload": "録画ファイルのアップロードを再試行",
  "streams.start": "配信を開始",
  "streams.stop": "配信を停止",
  "streams.update": "配信枠を更新",
  "streams.update_settings": "配信設定を更新",
  "streams.worker_event_test": "Workerイベントをテスト",
  "users.create": "ユーザーを作成",
  "users.delete": "ユーザーを削除",
  "users.disable": "ユーザーを無効化",
  "users.email_welcome": "ウェルカムメールを送信",
  "users.oauth_link.create": "ユーザーのOAuth連携を作成",
  "users.oauth_link.delete": "ユーザーのOAuth連携を解除",
  "users.force_password_change": "次回ログイン時のパスワード変更を要求",
  "users.lock": "ユーザーをロック",
  "users.reset_password": "ユーザーのパスワードをリセット",
  "users.update": "ユーザーを更新",
  "users.unlock": "ユーザーのロックを解除",
  "workers.assign": "Workerを割り当て",
  "workers.restart": "Workerを再起動",
  "workers.unassign": "Workerの割り当てを解除",
  "youtube.complete": "YouTube配信を終了",
  "youtube_outputs.create": "YouTube出力を作成",
  "youtube_outputs.delete": "YouTube出力を削除",
  "youtube_outputs.update": "YouTube出力を更新",
};

export function auditActionLabel(value?: string) {
  const raw = (value || "").trim();
  if (!raw) return "-";
  if (auditActionLabels[raw]) return auditActionLabels[raw];
  return raw
    .replace(/[_\-.]+/g, " ")
    .replace(/\b\w/g, (letter) => letter.toUpperCase());
}
