package httpapi

func (s *Server) registerServiceUpdaterRoutes() {
	s.mux.HandleFunc("POST /services/host-agent/policy", s.serviceHostAgentPolicy)
	s.mux.HandleFunc("POST /services/host-agent/runtime-token-rotations/{rotation_id}/credential/claim", s.claimRuntimeTokenRotationCredential)
	s.mux.HandleFunc("POST /services/host-agent/runtime-token-rotations/{rotation_id}/local-staged", s.acknowledgeRuntimeTokenRotationLocalStage)
	s.mux.HandleFunc("POST /services/host-agent/runtime-token-rotations/{rotation_id}/heartbeat-proof", s.proveRuntimeTokenRotationHeartbeat)
	s.mux.HandleFunc("POST /services/host-agent/runtime-token-rotations/{rotation_id}/activate", s.activateRuntimeTokenRotation)
	s.mux.HandleFunc("POST /services/host-agent/self-updates/{id}/grants", s.issueHostSelfUpdateGrant)
	s.mux.HandleFunc("POST /services/host-agent/self-update-grants/consume", s.consumeHostSelfUpdateGrant)
	s.mux.HandleFunc("POST /services/host-agent/runtime-token-rotations/{rotation_id}/cancel-ack", s.acknowledgeRuntimeTokenRotationCancel)
	s.mux.HandleFunc("POST /services/update-agent/bootstrap-jobs/claim", s.serviceUpdateHostBootstrapClaim)
	s.mux.HandleFunc("POST /services/update-agent/bootstrap-jobs/{id}/accept", s.serviceUpdateHostBootstrapAccept)
	s.mux.HandleFunc("POST /services/update-agent/bootstrap-jobs/{id}/report", s.serviceUpdateHostBootstrapReport)
	s.mux.HandleFunc("POST /services/update-jobs/claim", s.serviceSystemUpdateClaim)
	s.mux.HandleFunc("POST /services/update-jobs/{id}/report", s.serviceSystemUpdateReport)
	s.mux.HandleFunc("POST /services/update-jobs/{id}/mutation-grants", s.serviceSystemUpdateMutationGrantIssueV2)
	s.mux.HandleFunc("POST /services/update-jobs/{id}/mutation-grants/consume", s.serviceSystemUpdateMutationGrantConsumeV2)
	s.mux.HandleFunc("POST /services/runtime-identity/configuration", s.runtimeIdentityConfiguration)
	s.mux.HandleFunc("POST /services/host-agent/runtime-identity/stage", s.hostAgentRuntimeIdentityStage)
	s.mux.HandleFunc("POST /services/host-agent/runtime-identity/activate", s.hostAgentRuntimeIdentityActivate)
	s.mux.HandleFunc("POST /api/node-agent/heartbeat", s.nodeAgentHeartbeat)
	s.mux.HandleFunc("POST /api/node-agent/report", s.nodeAgentReport)
	s.mux.HandleFunc("POST /api/node-agent/events", s.serviceStreamEvent)
}

func (s *Server) registerSystemUpdateRoutes() {
	s.mux.HandleFunc("GET /system-updates", s.requirePermission("system_updates.read", s.listSystemUpdates))
	s.mux.HandleFunc("POST /system-updates", s.requirePermission("system_updates.execute", s.createSystemUpdate))
	s.mux.HandleFunc("POST /system-updates/{id}/cancel", s.requirePermission("system_updates.execute", s.cancelSystemUpdate))
	s.mux.HandleFunc("GET /system-updates/host-self-updates", s.requirePermission("system_updates.read", s.listHostSelfUpdates))
	s.mux.HandleFunc("POST /system-updates/hosts/{host_id}/self-updates", s.requirePermission("system_updates.execute", s.createHostSelfUpdate))
	s.mux.HandleFunc("POST /system-updates/host-self-updates/{id}/retry", s.requirePermission("system_updates.execute", s.retryHostSelfUpdate))
	s.mux.HandleFunc("POST /system-updates/host-self-updates/{id}/cancel", s.requirePermission("system_updates.execute", s.cancelHostSelfUpdate))
	s.mux.HandleFunc("GET /system-updates/updaters/{id}/settings", s.requirePermission("system_updates.read", s.getUpdaterPolicy))
	s.mux.HandleFunc("PUT /system-updates/updaters/{id}/settings", s.requirePermission("system_updates.execute", s.updateUpdaterPolicy))
	s.mux.HandleFunc("POST /system-updates/updaters/{id}/pull-ownership/activate", s.requirePermission("system_updates.execute", s.activatePullUpdaterOwnership))
	s.mux.HandleFunc("POST /system-updates/updaters/{id}/pull-ownership/deactivate", s.requirePermission("system_updates.execute", s.deactivatePullUpdaterOwnership))
	s.mux.HandleFunc("GET /system-updates/updaters/{id}/runtime-token-rotations/active", s.requirePermission("system_updates.read", s.getActiveRuntimeTokenRotation))
	s.mux.HandleFunc("POST /system-updates/updaters/{id}/runtime-token-rotations", s.requirePermission("system_updates.execute", s.stageRuntimeTokenRotation))
	s.mux.HandleFunc("POST /system-updates/updaters/{id}/runtime-token-rotations/{rotation_id}/cancel", s.requirePermission("system_updates.execute", s.cancelRuntimeTokenRotation))
	s.mux.HandleFunc("POST /system-updates/updaters/{id}/runtime-token-rotations/{rotation_id}/emergency-revoke", s.requirePermission("system_updates.execute", s.emergencyRevokeRuntimeTokenRotation))
	s.mux.HandleFunc("GET /system-updates/updaters/{id}/bootstrap-jobs", s.requirePermission("system_updates.read", s.listUpdateHostBootstrapJobs))
	s.mux.HandleFunc("POST /system-updates/updaters/{id}/bootstrap-jobs", s.requirePermission("system_updates.execute", s.createUpdateHostBootstrapJob))
}
