import { registerBootstrapCryptoCases } from "./system-updates-bootstrap-crypto-cases.mts";
import { registerPortValidationCases } from "./system-updates-port-validation-cases.mts";
import { registerPortRecoveryCases } from "./system-updates-port-recovery-cases.mts";
import { registerOwnershipCases } from "./system-updates-ownership-cases.mts";
import { registerRequestRecoveryCases } from "./system-updates-request-recovery-cases.mts";
import { registerUpdateResponseCases } from "./system-updates-response-cases.mts";
import { registerUpdaterSettingsCases } from "./system-updates-settings-cases.mts";
import { registerBootstrapPolicyCases } from "./system-updates-bootstrap-policy-cases.mts";
import { registerUpdatePresentationCases } from "./system-updates-presentation-cases.mts";
import { registerNodeAuthorityCases } from "./system-updates-node-authority-cases.mts";

registerBootstrapCryptoCases();
registerPortValidationCases();
registerPortRecoveryCases();
registerOwnershipCases();
registerRequestRecoveryCases();
registerUpdateResponseCases();
registerUpdaterSettingsCases();
registerBootstrapPolicyCases();
registerUpdatePresentationCases();
registerNodeAuthorityCases();
