import type { WorkerNode } from "@/types/domain";



export function createMockWorkerSeeds(baseTime: string): WorkerNode[] {
  return [
  {
    id: "worker-main",
    service_id: "worker-main",
    service_type: "worker",
    service_name: "本社メインWorker",
    status: "online",
    health_status: "healthy",
    assignment_role: "primary",
    current_stream_id: "stream-cable-morning",
    host: "worker-main.example.jp",
    port: 8443,
    ssl_enabled: true,
    public_url: "https://worker-main.example.jp",
    desired_endpoint: {
      host: "worker-main.example.jp",
      port: 18084,
      ssl_enabled: true,
      public_url: "https://worker-main.example.jp:18084",
    },
    applied_endpoint: {
      host: "worker-main.example.jp",
      port: 8443,
      ssl_enabled: true,
      public_url: "https://worker-main.example.jp:8443",
    },
    reported_endpoint: {
      host: "worker-main.example.jp",
      port: 8443,
      ssl_enabled: true,
      public_url: "https://worker-main.example.jp:8443",
    },
    endpoint_revision: 2,
    endpoint_status: "pending",
    version: "1.2.0",
    reported_version: "1.2.0",
    reported_commit: "8f71c21a4b2d",
    reported_build_date: "2026-07-02T07:40:00+09:00",
    reported_os: "linux",
    reported_arch: "amd64",
    last_heartbeat_at: "2026-07-02T09:00:00+09:00",
    heartbeat_age_sec: 4,
    capabilities: { overlay_events: true, caption_events: true, participant_state: true },
    reported_capabilities: { overlay_events: true, caption_events: true, participant_state: true },
    metrics: { cpu_percent: 32, memory_percent: 41, active_jobs: 2 },
  },
  {
    id: "encoder-main",
    service_id: "encoder-main",
    service_type: "encoder_recorder",
    service_name: "本社エンコーダー",
    status: "online",
    health_status: "healthy",
    assignment_role: "primary",
    current_stream_id: "stream-cable-morning",
    host: "encoder-main.example.jp",
    port: 8443,
    ssl_enabled: true,
    public_url: "https://encoder-main.example.jp",
    desired_endpoint: {
      host: "encoder-main.example.jp",
      port: 8443,
      ssl_enabled: true,
      public_url: "https://encoder-main.example.jp:8443",
    },
    applied_endpoint: {
      host: "encoder-main.example.jp",
      port: 8443,
      ssl_enabled: true,
      public_url: "https://encoder-main.example.jp:8443",
    },
    reported_endpoint: {
      host: "encoder-main.example.jp",
      port: 9443,
      ssl_enabled: true,
      public_url: "https://encoder-main.example.jp:9443",
    },
    endpoint_revision: 3,
    endpoint_status: "drift",
    version: "1.2.0",
    reported_version: "1.2.0",
    reported_commit: "41df9e2b701a",
    reported_build_date: "2026-07-02T07:42:00+09:00",
    reported_os: "linux",
    reported_arch: "amd64",
    last_heartbeat_at: "2026-07-02T08:59:58+09:00",
    heartbeat_age_sec: 6,
    capabilities: { rtmps_output: true, archive_upload: true, discord_audio_ingest: true },
    reported_capabilities: { rtmps_output: true, archive_upload: true, discord_audio_ingest: true },
    metrics: { cpu_percent: 48, memory_percent: 53, output_bitrate_kbps: 7800 },
  },
  {
    id: "worker-standby",
    service_id: "worker-standby",
    service_type: "worker",
    service_name: "庁舎スタンバイWorker",
    status: "online",
    health_status: "healthy",
    assignment_role: "standby",
    current_stream_id: "",
    host: "worker-city.example.jp",
    port: 8443,
    ssl_enabled: true,
    public_url: "https://worker-city.example.jp",
    version: "1.1.8",
    reported_version: "1.1.8",
    reported_commit: "ce2038a91d0b",
    reported_build_date: "2026-06-28T11:20:00+09:00",
    reported_os: "linux",
    reported_arch: "arm64",
    last_heartbeat_at: "2026-07-02T08:59:54+09:00",
    heartbeat_age_sec: 10,
    capabilities: { overlay_events: true, caption_events: true },
    reported_capabilities: { overlay_events: true, caption_events: true },
    metrics: { cpu_percent: 18, memory_percent: 29, active_jobs: 0 },
  },
  {
    id: "encoder-field",
    service_id: "encoder-field",
    service_type: "encoder_recorder",
    service_name: "現場持出エンコーダー",
    status: "degraded",
    health_status: "warning",
    assignment_role: "primary",
    current_stream_id: "stream-fm-special",
    host: "encoder-field.example.jp",
    port: 8443,
    ssl_enabled: true,
    public_url: "https://encoder-field.example.jp",
    version: "1.1.4",
    reported_version: "1.1.4",
    reported_commit: "ab96c1d0027e",
    reported_build_date: "2026-06-25T15:10:00+09:00",
    reported_os: "linux",
    reported_arch: "amd64",
    last_heartbeat_at: "2026-07-02T08:57:40+09:00",
    heartbeat_age_sec: 140,
    capabilities: { rtmps_output: true, archive_upload: true },
    reported_capabilities: { rtmps_output: true, archive_upload: true },
    metrics: { cpu_percent: 76, memory_percent: 68, output_bitrate_kbps: 0 },
  },
  {
    id: "discord-main",
    service_id: "discord-main",
    service_type: "discord_bot",
    service_name: "制作Discord Bot",
    status: "online",
    health_status: "healthy",
    assignment_role: "primary",
    current_stream_id: "stream-cable-morning",
    host: "discord-main.example.jp",
    port: 8443,
    ssl_enabled: true,
    public_url: "https://discord-main.example.jp",
    version: "1.2.0",
    reported_version: "1.2.0",
    reported_commit: "529b7e14f08c",
    reported_build_date: "2026-07-02T07:45:00+09:00",
    reported_os: "linux",
    reported_arch: "amd64",
    last_heartbeat_at: "2026-07-02T08:59:59+09:00",
    heartbeat_age_sec: 5,
    capabilities: { audio_capture: true, audio_stream_forward: true },
    reported_capabilities: { audio_capture: true, audio_stream_forward: true },
    metrics: { audio_forward_active: 1 },
  },
  {
    id: "host-agent-main",
    service_id: "host-agent-main",
    service_type: "update_agent",
    service_name: "本社 Host Agent",
    description: "本社ホストの更新状態を外向き接続で報告",
    transport_mode: "pull_v2",
    execution_host_id: "host-main",
    ownership_epoch: 3,
    status: "online",
    health_status: "healthy",
    version: "1.8.0",
    reported_version: "1.8.0",
    reported_os: "linux",
    reported_arch: "amd64",
    last_heartbeat_at: "2026-07-02T09:00:00+09:00",
    heartbeat_age_sec: 4,
    reported_capabilities: { host_pull_v2: true },
  },
  {
    id: "observability-main",
    service_id: "observability-main",
    service_type: "observability",
    service_name: "監視サービス",
    status: "online",
    health_status: "healthy",
    host: "monitor.example.jp",
    port: 443,
    ssl_enabled: true,
    public_url: "https://monitor.example.jp",
    desired_endpoint: {
      host: "monitor.example.jp",
      port: 443,
      ssl_enabled: true,
      public_url: "https://monitor.example.jp",
    },
    applied_endpoint: {
      host: "monitor.example.jp",
      port: 443,
      ssl_enabled: true,
      public_url: "https://monitor.example.jp",
    },
    reported_endpoint: {
      host: "127.0.0.1",
      port: 18090,
      ssl_enabled: false,
      public_url: "http://127.0.0.1:18090",
    },
    endpoint_revision: 7,
    endpoint_status: "applied",
    version: "1.1.3",
    reported_version: "1.1.3",
    reported_commit: "814b61b049f2",
    reported_build_date: "2026-07-02T07:50:00+09:00",
    reported_os: "linux",
    reported_arch: "amd64",
    last_heartbeat_at: baseTime,
    heartbeat_age_sec: 4,
  },
];
}
